export const productsList = [
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/PmyqDf7/item1.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/8rjwwFX/item2.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/9p2WrkX/item3.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/sWp2Nhd/item4.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: false,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/ZH0HT4W/item5.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/QFH3w5c/item6.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: false,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/4SWr9Wf/item7.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/r55Lk9n/item8.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 9,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/PtdL971/item9.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: true,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 10,
    title: "Basic Crew Neck Tee",
    thumbnail: "https://i.ibb.co/k9Y6scW/item10.png",
    color: "Black",
    price: "44.00",
    amount: 1,
    new: false,
    discount: false,
    discountAmout: "10%",
  },
];
